project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - reports/*.qmd

execute:
  freeze: auto

website:
  title: "DataSHIELD Test Reports"
  sidebar:
    style: docked
    search: false
    contents: auto

format:
  html:
    theme: cosmo
    toc: false
    self-contained: false
    embed-resources: false
    code-fold: false
    smooth-scroll: true
